import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

/* ATOMS */

/* Componentes são funcões retornando html*/
function Title(content: any) {
  return <title>content</title>
}
/* Componente com children dentro */
function PageTitle(props: any) {
  return <h1 className={styles.title}>{props.children}</h1>
}

function Container(props:any) {
  return <div className={styles.container}>{props.children}</div>
}

function Card(props:any) {
  return <a href={props.link} className={styles.card}>{props.children}</a>
}


function Footer() {
  return (
    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  )
}

function Description(props:any) {
  return (
    <p className={styles.description}>
      {props.children}
    </p>
  )
}

 /*MOLECULES*/

/* Exemplo de molécula (componente usando outro dentro de si) */
function DefaultHeader() {
  return (
    <Head>
      <Title content="Front Next.js app"/>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

/* ORGS */
function IndexCardGrid() {
  return  (
    <div className={styles.grid}>
      <Card link="https://nextjs.org/docs">
        <h2>Documentation &rarr;</h2>
        <p>Find in-depth information about Next.js features and API.</p>
      </Card>

      <Card link="https://nextjs.org/learn">
        <h2>Learn &rarr;</h2>
        <p>Learn about Next.js in an interactive course with quizzes!</p>
      </Card>

      <Card
        link="https://github.com/vercel/next.js/tree/canary/examples"
      >
        <h2>Examples &rarr;</h2>
        <p>Discover and deploy boilerplate example Next.js projects.</p>
      </Card>

      <Card
        link="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      >
        <h2>Deploy &rarr;</h2>
        <p>
          Instantly deploy your Next.js site to a public URL with Vercel.
        </p>
      </Card>
    </div>
  )
}

function MainBody() {
  return (
    <main className={styles.main}>
      <PageTitle>
        Welcome to <a href="https://nextjs.org">Thiago!</a>
      </PageTitle>
      <Description>
        Get started by editing{' '}
        <code className={styles.code}>pages/index.tsx</code>
      </Description>
      <IndexCardGrid/>
    </main>
  )
}

const Home: NextPage = () => {
  return (
    <Container>
      <DefaultHeader/>
      <MainBody/>
      <Footer/>
    </Container>
  )
}

export default Home
